name: Deploy index page

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate index.html
        run: |
          mkdir -p site
          echo '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Advent of Code Solutions</title></head><body>' > site/index.html
          echo '<table border="1">' >> site/index.html
          echo '<tr><th>Day</th><th>a.cpp lines</th><th>b.cpp lines</th></tr>' >> site/index.html
          for day in $(seq -w 1 25); do
            dir="2024/$day"
            a_lines=""
            b_lines=""
            if [ -f "$dir/a.cpp" ]; then
              a_lines=$(wc -l < "$dir/a.cpp" | xargs)
            fi
            if [ -f "$dir/b.cpp" ]; then
              b_lines=$(wc -l < "$dir/b.cpp" | xargs)
            fi
            echo "<tr><td>$day</td><td>${a_lines}</td><td>${b_lines}</td></tr>" >> site/index.html
          done
          echo '</table></body></html>' >> site/index.html
      - uses: actions/upload-pages-artifact@v1
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1

